{% set name = "onedrivedownloader" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/onedrivedownloader-{{ version }}.tar.gz
  sha256: 4ce25960fd407790eae3af1880df60d6bfd52d0176e8f058ec5d5c4e1470ac55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - requests
    - tqdm

test:
  imports:
    - onedrivedownloader
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/onedrivedownloader
  summary: Python utility to download files through OneDrive
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/loribonna/onedrivedownloader

extra:
  recipe-maintainers:
    - goanpeca
    - loribonna
